"""add_priority_and_checklist

Revision ID: 6c1333c4d5de
Revises: 8f515ddf851e
Create Date: 2026-05-02 14:54:34.364398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c1333c4d5de'
down_revision: Union[str, None] = '8f515ddf851e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
